[package]
name = "nulloc"
version = "0.1.0"
authors = ["Hao Shi <shisoftgenius@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
lazy_static = "*"
log = "*"
lfmap = { git = "https://github.com/shisoft/lfmap.rs", branch = "develop" }

[lib]
name = "nulloc"
crate-type = ["rlib", "dylib"]